// magic-oxfmt-config ignores `**/CHANGELOG.md` itself, so the local
// re-declaration this file used to carry is gone. The `withoutIgnorePatterns`
// opt-out 1.2.0 added is for repos that hand-write their changelog; this one's
// is generated by @release-it/conventional-changelog, so the default is right.
export { default } from "magic-oxfmt-config";
